### ISSUE TITLE
Plugin "netlify-plugin-fetch-feeds" internal error

### ISSUE THREAD

**Issue by twopix** [philhawksworth/netlify-plugin-fetch-feeds#16]
Could not import plugin:
Error: The module '/opt/build/repo/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).

While loading "netlify-plugin-fetch-feeds" from netlify.toml and package.json at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at bindings (/opt/build/repo/node_modules/bindings/bindings.js:112:48) at Object.<anonymous> (/opt/build/repo/node_modules/node-expat/lib/node-expat.js:4:34) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) at Module.load (node:internal/modules/cjs/loader:981:32)

Error properties: { code: 'ERR_DLOPEN_FAILED' }

**Comment by MarcoZehe** [comment]
I am running into the same issue. In addition, this plugin also prevents local `npm install` commands from working on M1 Macs nowadays with build error when precompiling binaries for node-expat. My Eleventy build that also uses this plugin would not work and doesn't deploy on Netlify. Perhaps a different/more up-to-date XML parser is the solution.

**Comment by anhsabmt** [comment]
Same problem.

**Comment by davatron5000** [comment]
FYI I had this problem but it was due to an old version of Node set in my Netlify Admin. 

To fix, I went to `Netlify Admin > mysite.com > Site Configuration > Build & Deploy > Dependency Mangament`

And from there, I clicked `Configure` and set it to the latest version of Node.

![dropdown for selecting node.js version in netlify admin with the last 4 major stable versions of node listed](https://github.com/philhawksworth/netlify-plugin-fetch-feeds/assets/42218/1ad08b1d-e80b-48ef-b9e0-5607941feb66)

Hope this helps future folks.
